#created by @PythonWhizKid
#Dictionary created with the help of A.I. tools
from time import sleep
import random
sleep(1)
print("Welcome to Word Guesser by @PythonWhizKid")
sleep(1)
dict = {
    "fantasy": "A genre of imaginative fiction involving magic and adventure",
    "dancing": "The activity of moving rhythmically to music",
    "honesty": "The quality of being truthful and trustworthy",
    "prosper": "To thrive or succeed, especially financially",
    "journey": "A long trip or expedition",
    "freedom": "The state of being free or unrestricted",
    "healthy": "In good physical or mental condition",
    "justice": "Fairness or reasonableness, especially in the administration of law",
    "believe": "To accept as true or real",
    "mystery": "Something that is difficult or impossible to understand or explain",
    "bravery": "Courageous behavior or character",
    "fortune": "A large amount of wealth or success",
    "silence": "The absence of sound or noise",
    "support": "To give assistance, encouragement, or approval to",
    "disease": "A disorder of structure or function in a human, animal, or plant",
    "history": "The study of past events",
    "program": "A series of coded software instructions to control the operation of a computer",
    "ancient": "Belonging to the very distant past",
    "genuine": "Authentic or real",
    "freight": "Goods transported by truck, train, ship, or aircraft",
    "justice": "The quality of being fair and reasonable",
    "victory": "The act of defeating an opponent in a battle, game, or competition",
    "explore": "To travel through an unfamiliar area in order to learn about it",
    "content": "In a state of peaceful happiness",
    "venture": "A risky or daring journey",
    "promise": "A declaration that one will do or refrain from doing something",
    "proceed": "To continue with a course of action",
    "perfect": "Having all the required or desirable elements, qualities, or characteristics",
    "ancient": "Belonging to the very distant past",
    "mansion": "A large, impressive house",
    "scenery": "The natural features of a landscape",
    "liberty": "The state of being free within society from oppressive restrictions",
    "journey": "An act of traveling from one place to another",
    "quality": "The standard of something as measured against other things of a similar kind",
    "realize": "To become fully aware of something as a fact",
    "request": "To politely ask for something",
    "remark": "To say or mention casually",
    "success": "The accomplishment of an aim or purpose",
    "thought": "An idea or opinion produced by thinking",
    "victory": "An instance of winning in a competition or struggle",
    "academy": "A place of study or training in a special field",
    "account": "A record of financial transactions",
    "bargain": "An agreement between parties concerning the sale of property or goods",
    "captain": "The person in command of a ship, aircraft, or sports team",
    "central": "Situated at the center",
    "college": "An educational institution or establishment",
    "combine": "To unite or merge",
    "compose": "To create or write",
    "conduct": "The manner in which a person behaves",
    "country": "A nation with its own government, occupying a particular territory",
    "distant": "Far away or remote in space",
    "episode": "An event or a group of events occurring as part of a larger sequence",
    "exclaim": "To cry out suddenly, especially in surprise, anger, or excitement",
    "failure": "Lack of success in accomplishing a goal or purpose",
    "feature": "A distinctive attribute or aspect of something",
    "genuine": "Truly what something is said to be",
    "gravity": "The force that attracts objects toward the center of the Earth",
    "history": "The study of past events",
    "initial": "Existing or occurring at the beginning",
    "inquiry": "The act of seeking information or knowledge",
    "justice": "Fairness or reasonableness, especially in the administration of law",
    "kitchen": "A room or area where food is prepared and cooked",
    "liberal": "Open to new behavior or opinions and willing to discard traditional values",
    "measure": "To ascertain the size, amount, or degree of something",
    "mission": "An important assignment carried out for political, religious, or commercial purposes",
    "natural": "Existing in or caused by nature, not made or caused by humankind",
    "outlook": "A person's point of view or general attitude towards life",
    "package": "An object or group of objects wrapped in paper or packed in a box",
    "plastic": "A synthetic material made from a wide range of organic polymers",
    "primary": "Of chief importance, principal",
    "quality": "The standard of something as measured against other things of a similar kind",
    "realize": "To become fully aware of something as a fact",
    "related": "Connected or associated with something else",
    "routine": "A sequence of actions regularly followed",
    "section": "A separate part of something",
    "serious": "Demanding or characterized by careful consideration or application",
    "session": "A meeting or period devoted to a particular activity",
    "society": "The aggregate of people living together in a more or less ordered community",
    "special": "Better, greater, or otherwise different from what is usual",
    "student": "A person who is studying at a school or college",
    "subject": "A person or thing that is being discussed, described, or dealt with",
    "support": "To give assistance, encouragement, or approval to",
    "teacher": "A person who teaches, especially in a school",
    "typical": "Having the distinctive qualities of a particular type or group",
    "upgrade": "To raise something to a higher standard",
    "venture": "A risky or daring journey or undertaking",
    "village": "A group of houses and associated buildings, larger than a hamlet",
    "weather": "The state of the atmosphere at a particular place and time",
    "wonder": "A feeling of amazement or admiration caused by something beautiful or remarkable",
    "abandon": "To leave or desert someone or something",
    "account": "A record of financial transactions",
    "balance": "An even distribution of weight",
    "bargain": "An agreement between parties concerning the sale of property or goods",
    "catalog": "A complete list of items, typically arranged in systematic order",
    "citizen": "A legally recognized member of a country",
    "compose": "To create or write",
    "conduct": "The manner in which a person behaves",
    "consult": "To seek information or advice from someone",
    "counter": "A flat surface over which goods are sold or served",
    "culture": "The customs, arts, social institutions, and achievements of a particular nation or people",
    "decline": "To become smaller, fewer, or less",
    "deserve": "To be worthy of or entitled to",
    "display": "To show or exhibit",
    "economy": "The wealth and resources of a country or region",
    "emotion": "A strong feeling, such as joy, anger, or sadness",
    "expense": "The cost incurred in or required for something",
    "factory": "A building or group of buildings where goods are manufactured",
    "fashion": "A popular trend in clothing, hairstyles, or behavior",
    "fiction": "Imaginative or invented storytelling",
    "frequent": "Occurring or done on many occasions",
    "generate": "To produce or create",
    "graduate": "To successfully complete a course of study or training",
    "hospital": "An institution providing medical and surgical treatment",
    "identify": "To recognize or establish the identity of someone or something",
    "imagine": "To form a mental image or concept of something",
    "impress": "To make a positive impact or influence on someone",
    "inspect": "To examine closely and critically",
    "install": "To set up or establish",
    "justice": "Fairness or reasonableness, especially in the administration of law",
    "lecture": "An educational talk given to an audience",
    "medical": "Relating to the science or practice of medicine",
    "mention": "To refer to briefly or casually",
    "mixture": "A combination of different elements or substances",
    "observe": "To see, notice, or perceive",
    "opinion": "A view or judgment formed about something",
    "oppose": "To be against or in conflict with something",
    "patient": "A person receiving medical treatment",
    "practice": "The repeated performance or exercise of an activity",
    "predict": "To say or estimate that something will happen in the future",
    "present": "Existing or occurring now",
    "produce": "To make or manufacture",
    "promise": "A declaration that one will do or refrain from doing something",
    "protect": "To keep safe from harm or danger",
    "publish": "To make information available to the public",
    "purchase": "To acquire something in exchange for money",
    "reflect": "To think deeply or carefully about something",
    "release": "To set free or allow to escape",
    "replace": "To exchange something",
    "reserve": "To arrange for something to be kept for a particular purpose",
    "restore": "To bring back to a former or original condition",
    "routine": "A sequence of actions regularly followed",
    "scatter": "To throw or distribute in various directions",
    "schedule": "A plan or timetable for a series of events or activities",
    "science": "The intellectual and practical activity encompassing the systematic study of the structure and behavior of the physical and natural world",
    "scratch": "To mark or damage the surface of something with a sharp object",
    "section": "A separate part of something",
    "serious": "Demanding or characterized by careful consideration or application",
    "session": "A meeting or period devoted to a particular activity",
    "shelter": "A place providing protection or refuge",
    "shrink": "To become smaller in size or amount",
    "silence": "The absence of sound or noise",
    "similar": "Resembling or alike in appearance or nature",}

for w, meaning in dict.items():
    w = random.choice(list(dict.keys()))
    print(w[0:3])
    sleep(0.8)
    print("Guess the 7/8 letter word (Starting 3 letters are given")
    sleep(0.8)
    print(dict[w])
    sleep(0.8)
    inp = input("Write your answer: ")
    
    
    if inp ==  w:
        print("Well done")
        c = input("Enter any letter to continue: ")
        continue
    else:
        print("Better luck next time! The correct word is: ", w)
        cc = input("Enter any letter to continue: ")
        continue
