from time import sleep
crush_name = "crush" #Write crush name here
print("Welcome to soul searcher")
sleep(1)
p = input("Enter your name: ")
sleep(0.5)
d = input("Enter your country:  ")
sleep(0.5)
t = input("Enter time of birth: ")
sleep(2)
name = ['Charlotte', 'Amelia', 'Emma', 'Mia', 'Isabella', 'Ava', 'Elizabeth', 'Olivia', 'Ella', 'Sophia', 'Evelyn', 'Scarlett', 'Emily', 'Eleanor', 'Harper', 'Grace', 'Luna', 'Alice', 'Chloé', 'Abigail', 'Aurora', 'Lily', 'Hazel', 'Hannah', 'Ivy', 'Victoria', 'Emilia', 'Zoey', 'Naomi', 'Hannah', 'Lucy', 'Elena', 'Lillian', 'Maya', 'Leah', 'Paisley', 'Addison', 'Natalie', 'Valentina', 'Everly', 'Delilah', 'Leilani', 'Madelyn', 'Kinsley', 'Ruby', 'Sophie', 'Alice', 'Genesis', 'Claire', 'Audrey', 'Sadie', 'Aaliyah', 'Clara', 'Hadley', 'Julia', 'Piper', 'Juniper', 'Parker', 'Brielle', 'Eden', 'Remi', 'Josie', 'Rose', 'Arya', 'Eliza', 'Charlie', 'Peyton', 'Daisy', 'Lucia', 'Millie', 'Margaret', 'Freya', 'Melanie', 'Elliana', 'Adalynn', 'Alina', 'Emersyn', 'Sienna', 'Mary', 'Isabelle', 'Alaia', 'Esther', 'Sloane', 'Mackenzie', 'Amara', 'Ximena', 'Sage', 'Cecilia', 'Valeria', 'Reagan', 'Valerie', 'Catalina', 'River', 'Magnolia', 'Kehlani', 'Summer', 'Ashley', 'Andrea', 'Isabel', 'Oakley', 'Olive', 'Oaklynn', 'Ember', 'Kaylee', 'Georgia', 'Juliette', 'Anastasia', 'Genevieve', 'Katherine', 'Blakely', 'Reese', 'Amaya', 'Emerson', 'Brianna', 'June', 'Alani', 'Lainey', 'Arianna', 'Rosalie', 'Sara', 'Jasmine', 'Ruth', 'Adalyn', 'Ada', 'Bailey', 'Ariella', 'Wren', 'Myla', 'Khloe', 'Callie', 'Elsie', 'Alexandra', 'Ryleigh', 'Faith', 'Norah', 'Margot', 'Zuri', 'Journee', 'Aspen', 'Gemma', 'Kylie', 'Molly', 'Blake', 'Zara', 'Alaina', 'Alana', 'Brynlee', 'Amy','Hailey']
name1 = ['Josephine', 'Autumn', '', 'Brooklyn', 'Quinn', 'Kennedy', 'Cora', 'Savannah', 'Caroline', 'Athena', 'Natalia', 'Hailey', 'Aubrey', 'Emery', 'Anna', 'Iris', 'Bella', 'Eloise', 'Skylar', 'Jade', 'Gabriella', 'Ariana', 'Maria', 'Adeline', 'Lydia', 'Sarah', 'Nevaeh', 'Serenity', 'Liliana', 'Ayla', 'Everleigh', 'Raelynn', 'Allison', 'Madeline', 'Vivian', 'Maeve', 'Lyla', 'Samantha', 'Rylee', 'Eva', 'Melody',]
print("Searching for potential souls")
sleep(2)
print("Trying hard....")
sleep(1)
print("325642367543564366545995347454435 of 3543567866457856543545678647657676765 souls done")
sleep(1)
print("processing...")
sleep(0.3)
print(name1)
sleep(0.8)
print(name)
sleep(2)
print(name)
sleep(0.8)
print(name1)
sleep(0.8)
print(name)
sleep(5)
print("!!!!!!!!!!!")
sleep(0.8)
print("Match found!")
sleep(0.8)
print("xxxxxxxxxxxxxxxxxxxxxxxx")
sleep(1)
#write name of crush
print(crush_name, " is the one")
sleep(1)
print("xxxxxxxxxxxxxxxxxxxxxxxx")
sleep(1)
print("Fee- $700 | Thanks for using :)")
